### ISSUE TITLE
Add initial pages of documentation and protocols/manuals

### ISSUE THREAD

**Issue by mrueschman** [nsrr/ccshs-documentation#1]

**Comment by mrueschman** [comment]
@michellereid 

Something to start with.

About this Study

> The Cleveland Children’s Sleep and Health Study (CCSHS) is one of the largest population-based pediatric cohorts studied with objective sleep studies, and probably one with the largest minority representation. The cohort includes 907 children, studied at ages 8-11 yrs. with in-home sleep studies, acoustic reflectometry, anthropometry, spirometry, BP, and NP and behavioral assessments. The cohort is a stratified random sample of full-term (FT) and PT children, born between 1988-1993, identified from the birth records of 3 Cleveland area hospitals.

Any manuals or protocols, particularly for the TREC visit (3rd visit after Peds and Teenz), seem difficult to find. The project folder on RFA is here: \rfa01\bwh-sleepepi-home\projects\cohorts\TREC

**Comment by michellereid** [comment]
[1bad965](https://github.com/nsrr/ccshs-documentation/commit/1bad965c72e15a78fc4064ffc22b40e592870287)
